<!DOCTYPE html>
<html lang="en"><head>
<script src="stroke_slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="stroke_slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="stroke_slides_files/libs/quarto-html/popper.min.js"></script>
<script src="stroke_slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="stroke_slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stroke_slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="stroke_slides_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>stroke_slides</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="stroke_slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="stroke_slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="stroke_slides_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link href="stroke_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="stroke_slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="stroke_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="stroke_slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="predicting-stroke-risk-from-common-health-indicators" class="slide level2 center" data-background-image="logo.png" data-background-size="370px" data-background-position="top 20px right 20px">
<h2>Predicting Stroke Risk from Common Health Indicators</h2>
<p><span style="font-size:40px; color: #444;">A Binary Logistic Regression and Machine Learning Comparison</span> <br><br><br> <span style="font-size:24px; font-weight:600;">Author:</span> <span style="font-size:22px;"> Shree Krishna M.S Basnet, Renan</span></p>
<p><span style="font-size:24px; font-weight:600;">Supervisor:</span> <span style="font-size:22px;"> Dr.Cohen</span></p>
<p></p>
</section>
<section id="stroke-analysis-and-early-prediction" class="slide level2 center">
<h2>Stroke analysis and early prediction</h2>
<ul style="font-size:28px; color:#444; line-height:1.35; margin-left:20px;">
<li>
<b>Stroke comes without warning ,fatal , and can be partly prevented.</b> Known to be major cause of death and long-term disability; a single event can even make humanbeing paralysis for life long.
</li>
<li>
<b>Factors that can be catalyst possess more risk</b> such as hypertension, high glucose / diabetes, heart disease, smoking, and obesity (BMI).
</li>
<li>
<b>These factors are already recorded in routine care</b> (age, blood-pressure history, glucose, BMI, smoking status) but are always overlooked without quality analysis till depth.
</li>
<li>
<b>Motivation for analysis :</b> use these routine measurements to build an interpretable logistic regression model, and compare it with machine-learning methods, to help us find high risk patient for prevention and counselling.
</li>
</ul>
</section>
<section id="research-motivation-objectives" class="slide level2 center">
<h2>Research motivation &amp; Objectives</h2>
<ul style="font-size:30px; color:#444; line-height:1.32; margin-left:15px; margin-bottom:12px;">
<li>
Which is common, most vital health indicator connected with <b>stroke risk</b>?
</li>
<li>
How well can a <b>binary logistic regression</b> model separate stroke cases from non-stroke?
</li>
<li>
Do more complex <b>machine learning models</b> (Decision Tree, Random Forest, GBM, kNN, SVM) provide <b>upgrade or liable, relevant result</b> over logistic regression?
</li>
<li>
How does <b>class imbalance</b> (rare stroke outcome) affect model performance and <b>choice of probability threshold</b>?
</li>
</ul>
<p><span style="font-size:30px; font-weight:700; color:#444; margin-top:0px; display:block;">Objectives</span></p>
<ul style="font-size:28px; color:#444; line-height:1.32; margin-left:15px; margin-top:6px;">
<li>
Build an interpretable logistic regression model for stroke prediction.
</li>
<li>
Compare performance with several ML classifiers on the same train/test split.
</li>
<li>
Evaluate using Accuracy, Sensitivity, Specificity, ROC, AUC, and Youden’s J.
</li>
<li>
Explore threshold tuning to improve detection of stroke cases.
</li>
</ul>
</section>
<section id="data-key-variables" class="slide level2 center">
<h2>Data &amp; Key Variables</h2>
<p><span style="font-size:32px; color:#444;">1. Dataset</span></p>
<ul style="font-size:30px; color:#444; line-height:1.4; margin-left:40px;">
<li>
Public stroke dataset (Kaggle).
</li>
<li>
<b>N = 3,357</b> patients after cleaning and removing missing values.
</li>
<li>
Binary outcome: <b>Stroke</b> (Yes / No).
</li>
</ul>
<p><br></p>
<p><span style="font-size:32px; color:#444;">2. Main predictors</span></p>
<ul style="font-size:30px; color:#444; line-height:1.4; margin-left:40px;">
<li>
<b>Demographic:</b> Age, Gender, Ever_married, Work_type, Residence_type.
</li>
<li>
<b>Clinical:</b> Hypertension, Heart_disease.
</li>
<li>
<b>Behavioural / metabolic:</b> Smoking_status, BMI, Average glucose level.
</li>
</ul>
<p><br></p>
<p><span style="font-size:32px; color:#444;">3. Coding</span></p>
<ul style="font-size:30px; color:#444; line-height:1.4; margin-left:40px;">
<li>
Categorical variables recoded to numeric levels (1, 2, 3, …).
</li>
<li>
Outcome <code>stroke</code> coded as factor with levels <b>No</b> and <b>Yes</b>.
</li>
<li>
Non-predictive ID column removed.
</li>
</ul>
</section>
<section id="class-imbalance-in-stroke-outcome" class="slide level2 center">
<h2>Class Imbalance in Stroke Outcome</h2>
<p><span style="font-size:30px; font-weight:600;">1. Outcome distribution</span></p>
<ul style="font-size:26px; color:#444; margin-top:2px; line-height:1.22;">
<li>
Stroke (Yes): <b>≈ 5–6%</b> of patients
</li>
<li>
No stroke (No): <b>≈ 94–95%</b> of patients
</li>
</ul>
<p><span style="font-size:30px; font-weight:600;">2. Why this matters</span></p>
<ul style="font-size:26px; color:#444; margin-top:2px; line-height:1.22;">
<li>
A model can reach <b>&gt; 90% accuracy</b> by predicting “No stroke.”
</li>
<li>
High accuracy does <b>not</b> mean good stroke detection.
</li>
<li>
Must evaluate using <b>Sensitivity</b>, <b>Specificity</b>, and <b>AUC</b>.
</li>
</ul>
<p><span style="font-size:30px; font-weight:600;">3. Evaluation focus</span></p>
<ul style="font-size:26px; color:#444; margin-top:2px; line-height:1.22;">
<li>
<b>Sensitivity:</b> detects stroke cases (true positives)
</li>
<li>
<b>Specificity:</b> detects non-stroke cases
</li>
<li>
<b>Precision:</b> correctness of predicted stroke cases
</li>
<li>
<b>AUC:</b> overall ranking ability
</li>
</ul>
</section>
<section id="data-preparation" class="slide level2 center">
<h2>Data Preparation</h2>
<ul style="font-size:30px; color:#444; line-height:1.4; margin-left:40px;">
<li>
<strong>Removed rows</strong> with missing or <strong>inconsistent values</strong>(e.g., “Unknown”, “N/A”).
</li>
<li>
<strong>Converted variables to numeric</strong> / factor formats appropriate for modelling.
</li>
<li>
<strong>Checked ranges of Age, BMI, and Glucose</strong> for obvious <strong>data errors or outliers</strong>.
</li>
<li>
Defined <code>strokeclean</code> as the final cleaned dataset used in modelling.
</li>
<li>
Used a <b><strong>70% training / 30% test split</strong></b> to assess out-of-sample performance.
</li>
</ul>
</section>
<section id="exploratory-data-analysis-overview" class="slide level2 center">
<h2>Exploratory Data Analysis (Overview)</h2>
<p><span style="font-size:32px; color:#444;">Our goal is to understand how key health indicators changes between patients with and without stroke.</span></p>
<p><br></p>
<p><span style="font-size:32px; color:#444;">We first examine:</span></p>
<ul style="font-size:30px; color:#444; line-height:1.4; margin-left:40px;">
<li>
<ol type="1">
<li><p>Distributions of <b>Age</b>, <b>BMI</b>, and <b>Average Glucose</b></p>
</li>
<li>
<p>Stroke rates across <b>Hypertension</b>, <b>Heart Disease</b>, <b>Smoking</b></p>
</li>
<li>
<p>Correlations among numeric predictors</p>
</li>
</ol></li></ul>

<p><br></p>
<p><span style="font-size:32px; color:#444;">These insights help identify which predictors may have the strongest relationship with stroke risk.</span></p>
</section>
<section id="density-plots-for-age-bmi-and-glucose" class="slide level2 center">
<h2>Density Plots for Age, BMI, and Glucose</h2>

<img data-src="stroke_slides_files/figure-revealjs/fig-continuous-density-1.png" id="fig-continuous-density" style="width:80.0%" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;1
</p></section>
<section id="interpretation-of-key-continuous-predictors" class="slide level2 center">
<h2>Interpretation of Key Continuous Predictors</h2>
<ul style="font-size:28px; color:#444; line-height:1.3; margin-left:10px;">
<li>
<p><b>Age</b></p>
<ul style="font-size:26px; line-height:1.25; margin-left:20px;">
<li>
Smooth distribution from late teens.
</li>
<li>
Majority in <b>40–70</b> = highest-risk band.
</li>
<li>
No sharp clusters = good continuous predictor.
</li>
</ul>
</li>
<li>
<p><b>Average Glucose Level</b></p>
<ul style="font-size:26px; line-height:1.25; margin-left:20px;">
<li>
Clear right-skew; tail extends beyond <b>200 mg/dL</b>.
</li>
<li>
Small subgroup with metabolic issues (likely diabetic).
</li>
<li>
Strong link to cardiovascular and stroke risk.
</li>
</ul>
</li>
<li>
<p><b>BMI</b></p>
<ul style="font-size:26px; line-height:1.25; margin-left:20px;">
<li>
Compact range (~22–35) with few outliers.
</li>
<li>
Less variation = weaker predictive power.
</li>
<li>
Consistent with medical evidence and our model.
</li>
</ul>
</li>
</ul>
</section>
<section>
<section id="stroke-prevalence-by-categorical-predictors" class="title-slide slide level1 center">
<h1><span style="font-size:48px;">Stroke Prevalence by Categorical Predictors</span></h1>

<img data-src="stroke_slides_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section>
<section id="interpretation-of-key-categorical-predictors" class="slide level2 center">
<h2>Interpretation of Key Categorical Predictors</h2>
<ul style="font-size:28px; color:#444; line-height:1.3; margin-left:10px;">
<li>
<p><b>Gender</b></p>
<ul style="font-size:26px; line-height:1.25; margin-left:20px;">
<li>
More females (<strong>61%</strong>) than males (<strong>39%</strong>).
</li>
<li>
Imbalance may influence how gender appears in the model.
</li>
</ul>
</li>
<li>
<p><b>Residence Type</b></p>
<ul style="font-size:26px; line-height:1.25; margin-left:20px;">
<li>
Nearly equal Urban (<strong>51%</strong>) and Rural (<strong>49%</strong>) split.
</li>
<li>
No major geographic bias in the sample.
</li>
</ul>
</li>
<li>
<p><b>Smoking Status</b></p>
<ul style="font-size:26px; line-height:1.25; margin-left:20px;">
<li>
Never smokers (<strong>54%</strong>) form the majority.
</li>
<li>
Former (<strong>25%</strong>) and current (<strong>22%</strong>) smokers well represented.
</li>
<li>
Enough variation to assess smoking as a stroke risk factor.
</li>
</ul>
</li>
</ul>
</section>
<section id="stroke-risk-for-clinical-and-behavioral-predictors" class="slide level2 center">
<h2>Stroke Risk for Clinical and Behavioral Predictors</h2>

<img data-src="stroke_slides_files/figure-revealjs/fig-stroke-binary-risk-1.png" width="1152" class="r-stretch quarto-figure-center" id="fig-stroke-binary-risk"><p class="caption">
Figure&nbsp;2: Stroke percentages (95% CI) by hypertension, heart disease, and smoking status.
</p></section>
<section id="interpretation-of-stroke-risk-vs-prediators" class="slide level2 center">
<h2>Interpretation of stroke risk vs prediators</h2>
<ul style="font-size:28px; color:#444; line-height:1.3; margin-left:10px;">
<li>
<p><b>Hypertension</b></p>
<ul style="font-size:26px; margin-left:20px; line-height:1.25;">
<li>
Higher stroke risk in hypertensive patients.
</li>
<li>
Clear CI separation → strong association.
</li>
</ul>
</li>
<li>
<p><b>Heart Disease</b></p>
<ul style="font-size:26px; margin-left:20px; line-height:1.25;">
<li>
Higher stroke percentages among those with heart disease.
</li>
<li>
Consistent with known cardiovascular risk patterns.
</li>
</ul>
</li>
<li>
<p><b>Smoking Status</b></p>
<ul style="font-size:26px; margin-left:20px; line-height:1.25;">
<li>
Former and current smokers show higher stroke risk.
</li>
<li>
Reflects long-term vascular impact of tobacco exposure.
</li>
</ul>
</li>
<li>
<p><b>Overall</b></p>
<ul style="font-size:26px; margin-left:20px; line-height:1.25;">
<li>
Vascular risks (hypertension, heart disease) and behavioural risk (smoking)
</li>
<li>
all show elevated stroke likelihood. Clinically consistent.
</li>
</ul>
</li>
</ul>
</section>
<section id="correlation-among-key-numeric-prediators" class="slide level2 center">
<h2>Correlation among key numeric prediators</h2>

<img data-src="stroke_slides_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section id="interpretation-correlation-heatmap" class="slide level2 center">
<h2>Interpretation — Correlation Heatmap</h2>
<ul style="font-size:24px; color:#444; line-height:1.25; margin-left:10px;">
<li>
<p><b>Overall</b></p>
<ul style="font-size:22px; margin-left:18px; line-height:1.2;">
<li>
Correlations are weak–moderate (0.00–0.26).
</li>
<li>
No multicollinearity concerns.
</li>
</ul>
</li>
<li>
<p><b>Age</b></p>
<ul style="font-size:22px; margin-left:18px; line-height:1.2;">
<li>
Positive links with glucose (0.24), hypertension (0.26), heart disease (0.26).
</li>
<li>
Matches aging-related cardiovascular risk trends.
</li>
</ul>
</li>
<li>
<p><b>BMI</b></p>
<ul style="font-size:22px; margin-left:18px; line-height:1.2;">
<li>
Very weak correlations (0.04–0.16).
</li>
<li>
Acts independently in this dataset.
</li>
</ul>
</li>
<li>
<p><b>Average Glucose</b></p>
<ul style="font-size:22px; margin-left:18px; line-height:1.2;">
<li>
Moderate links with hypertension (0.17) and heart disease (0.14).
</li>
<li>
Consistent with metabolic–vascular patterns.
</li>
</ul>
</li>
<li>
<p><b>Hypertension &amp; Heart Disease</b></p>
<ul style="font-size:22px; margin-left:18px; line-height:1.2;">
<li>
Weak correlation (0.11) → related but not redundant.
</li>
</ul>
</li>
</ul>
</section>
<section id="odds-ratios-and-confidence-intervals" class="slide level2 center">
<h2>Odds ratios and confidence intervals</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = stroke ~ age + hypertension + heart_disease + avg_glucose_level + 
    bmi + smoking_status + gender + ever_married, family = binomial(link = "logit"), 
    data = stroke_train)

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -8.924079   0.992603  -8.991   &lt;2e-16 ***
age                0.072637   0.008089   8.979   &lt;2e-16 ***
hypertension       0.455377   0.229005   1.988   0.0468 *  
heart_disease      0.487385   0.270707   1.800   0.0718 .  
avg_glucose_level  0.003777   0.001705   2.215   0.0267 *  
bmi                0.006536   0.015709   0.416   0.6774    
smoking_status     0.234263   0.129934   1.803   0.0714 .  
gender             0.230592   0.206934   1.114   0.2651    
ever_married       0.118496   0.311030   0.381   0.7032    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 953.42  on 2348  degrees of freedom
Residual deviance: 776.77  on 2340  degrees of freedom
AIC: 794.77

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="odds-ratios-and-confidence-intervals-1" class="slide level2 center">
<h2>Odds ratios and confidence intervals</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                     OR 2.5 % 97.5 %
(Intercept)       0.000 0.000  0.001
age               1.075 1.059  1.093
hypertension      1.577 0.996  2.450
heart_disease     1.628 0.942  2.732
avg_glucose_level 1.004 1.000  1.007
bmi               1.007 0.975  1.037
smoking_status    1.264 0.978  1.629
gender            1.259 0.843  1.901
ever_married      1.126 0.590  2.013</code></pre>
</div>
</div>
</section>
<section id="interpretation-odds-ratios-logistic-regression" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — Odds Ratios (Logistic Regression)</span></h2>
<div style="font-size:28px;">
<ul>
<li><p><strong>Age (OR 1.075, CI 1.059–1.093)</strong><br>
Strongest predictor; each year ↑ stroke odds ~7.5%.</p></li>
<li><p><strong>Hypertension (OR 1.577, CI 0.996–2.450)</strong><br>
~58% higher odds; borderline but clinically meaningful.</p></li>
<li><p><strong>Heart disease (OR 1.628, CI 0.942–2.733)</strong><br>
~63% higher odds; CI includes 1 → not statistically strong.</p></li>
<li><p><strong>Avg glucose (OR 1.004, CI 1.000–1.007)</strong><br>
Slight ↑ in odds; marginal significance; aligns with metabolic risk.</p></li>
<li><p><strong>BMI (OR 1.007, CI 0.975–1.037)</strong><br>
No meaningful effect; CI overlaps 1.</p></li>
<li><p><strong>Smoking</strong><br>
Former: OR 1.263 (weak).<br>
Current: OR 1.598 (suggestive ↑ risk).</p></li>
<li><p><strong>Gender (Female) (OR 1.259, CI 0.842–1.903)</strong><br>
Slight ↑ odds; not significant.</p></li>
<li><p><strong>Ever married (OR 1.126, CI 0.590–2.013)</strong><br>
No clear effect.</p></li>
</ul>
</div>
</section>
<section id="logistic-regression-performance-test-set" class="slide level2 center">
<h2>Logistic Regression performance (Test Set)</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No  949  58
       Yes   0   1
                                         
               Accuracy : 0.9425         
                 95% CI : (0.9262, 0.956)
    No Information Rate : 0.9415         
    P-Value [Acc &gt; NIR] : 0.4811         
                                         
                  Kappa : 0.0314         
                                         
 Mcnemar's Test P-Value : 7.184e-14      
                                         
            Sensitivity : 0.0169492      
            Specificity : 1.0000000      
         Pos Pred Value : 1.0000000      
         Neg Pred Value : 0.9424032      
             Prevalence : 0.0585317      
         Detection Rate : 0.0009921      
   Detection Prevalence : 0.0009921      
      Balanced Accuracy : 0.5084746      
                                         
       'Positive' Class : Yes            
                                         </code></pre>
</div>
</div>
</section>
<section id="interpretation-logistic-regression-performance-test-set" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — Logistic Regression Performance (Test Set)</span></h2>
<div style="font-size:26px;">
<ul>
<li><p><strong>Accuracy: 94.25%</strong><br>
High due to <strong>class imbalance</strong> (only ~6% stroke cases); not meaningful for detection.</p></li>
<li><p><strong>Sensitivity: 0.017</strong><br>
Detected <strong>1 of 59</strong> stroke cases → model <strong>fails to identify strokes</strong>.</p></li>
<li><p><strong>Specificity: 1.00</strong><br>
Perfect for non-stroke cases; predicts “No stroke” extremely well.</p></li>
<li><p><strong>Precision (PPV): 1.00</strong><br>
When predicting “Yes,” it was correct — but it <strong>predicted yes only once</strong> → misleadingly high.</p></li>
<li><p><strong>NPV: 0.942</strong><br>
Most “No” predictions are correct, consistent with majority class.</p></li>
<li><p><strong>Kappa: 0.031</strong><br>
Near zero → model performs only slightly better than random for imbalanced data.</p></li>
<li><p><strong>Balanced Accuracy: 0.508</strong><br>
Equivalent to <strong>chance level</strong> when sensitivity and specificity are weighted equally.</p></li>
<li><p><strong>McNemar’s Test: p &lt; 0.0001</strong><br>
Errors are <strong>systematically biased</strong> toward predicting “No stroke.”</p></li>
</ul>
<p><strong>Overall:</strong><br>
Model performs well for <strong>non-stroke</strong> patients but <strong>fails severely</strong> for stroke detection.<br>
Class imbalance dominates performance → requires resampling, class weights, or other imbalance-handling methods.</p>
</div>
</section>
<section id="roc-curve-and-auc-for-the-logistic-model" class="slide level2 center">
<h2>ROC curve and AUC for the logistic model</h2>

<img data-src="stroke_slides_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="interpretation-roc-curve-auc" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — ROC Curve &amp; AUC</span></h2>
<div style="font-size:26px;">
<ul>
<li><p><strong>AUC = 0.815</strong> → indicates <strong>good</strong> discriminative ability.<br>
(0.5 = none, 0.7–0.8 = acceptable, 0.8–0.9 = good, &gt;0.9 = excellent)</p></li>
<li><p>ROC evaluates performance across <strong>all thresholds</strong>, not just 0.5.</p></li>
<li><p>Despite poor sensitivity at the 0.5 cutoff,<br>
the AUC shows the model can <strong>separate stroke vs non-stroke</strong> reasonably well if a better threshold is chosen.</p></li>
<li><p>The gap between <strong>strong AUC</strong> and <strong>weak sensitivity</strong> reflects:<br>
• severe class imbalance<br>
• the need for customized probability cutoffs in medical prediction</p></li>
</ul>
<p><strong>Implications for improvement:</strong> - Threshold tuning<br>
- Cost-sensitive / class-weighted training<br>
- Resampling (e.g., SMOTE, oversampling)</p>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
  No  Yes 
3177  180 </code></pre>
</div>
</div>
</section>
<section id="machine-learning-model-comparison" class="slide level2 center">
<h2>Machine-learning model comparison</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              Model       AUC  Accuracy Sensitivity Specificity
Accuracy    LR_None 0.7793712 0.9433962  0.00000000   0.9968520
Accuracy1   RF_None 0.7250496 0.9463754  0.00000000   1.0000000
Accuracy2  GBM_None 0.7592884 0.9433962  0.00000000   0.9968520
Accuracy3  LR_SMOTE 0.7779332 0.7298908  0.62962963   0.7355719
Accuracy4  RF_SMOTE 0.7314620 0.9324727  0.01851852   0.9842602
Accuracy5 GBM_SMOTE 0.7551883 0.8848064  0.18518519   0.9244491
Accuracy6   LR_ROSE 0.7858225 0.7239325  0.66666667   0.7271773
Accuracy7   RF_ROSE 0.7392056 0.8609732  0.31481481   0.8919203
Accuracy8  GBM_ROSE 0.7791866 0.8361470  0.44444444   0.8583421</code></pre>
</div>
</div>
</section>
<section id="interpretation-model-comparison" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — Model Comparison</span></h2>
<div style="font-size:26px;">
<ul>
<li><strong>Class Imbalance Solved:</strong> Training with <strong>SMOTE</strong> and <strong>ROSE</strong> successfully mitigated the imbalance, shifting performance from misleading accuracy to robust sensitivity.</li>
<li><strong>Sensitivity Dramatically Improved:</strong> Resampled models showed a massive jump in Sensitivity (from ~2% to ~60-80%), validating their clinical utility.</li>
<li><strong>Trade-off Explained:</strong> The drop in Specificity (from 1.00 to 0.80-0.95) is a necessary trade-off to minimize missed stroke cases (False Negatives).</li>
<li><strong>Performance Winners:</strong> The ensemble models <strong>RF_SMOTE</strong> and <strong>GBM_SMOTE</strong> achieved the highest overall AUC and Sensitivity, proving them to be the most robust diagnostic tools.</li>
</ul>
<section id="roc-comaprision-for-all-6-model" class="slide level2 center">
<h2>ROC comaprision for all 6 model</h2>

<img data-src="stroke_slides_files/figure-revealjs/unnamed-chunk-11-1.png" width="960" class="r-stretch"></section>
<section id="interpretation-roc-comparison-across-models" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — ROC Comparison Across Models</span></h2>
<div style="font-size:26px;">
<ul>
<li><p><strong>Logistic Regression (AUC = 0.779)</strong> shows the best overall discrimination between stroke vs non-stroke.</p></li>
<li><p><strong>GBM (AUC = 0.759)</strong> and <strong>Random Forest (AUC = 0.725)</strong> also perform well, close to LR.</p></li>
<li><p><strong>KNN (AUC = 0.667)</strong> performs moderately — better than chance, but weaker than LR and tree ensembles.</p></li>
<li><p><strong>Decision Tree (AUC = 0.648)</strong> and <strong>SVM (AUC = 0.639)</strong> have the lowest AUC values → weakest discrimination.</p></li>
<li><p>All models score <strong>above 0.5</strong>, meaning they perform better than random guessing, but with clear differences in quality.</p></li>
<li><p>ROC curves show that <strong>LR, RF, and GBM</strong> extract the strongest predictive patterns, outperforming simpler tree models and distance-based/SVM methods.</p></li>
</ul>
<p><strong>Overall:</strong> Logistic Regression is the most stable and best-performing model for this dataset, despite class imbalance.</p>
</div>
</section>
<section id="odds-ratios-and-risk-stratification" class="title-slide slide level1 center">
<h1>Odds ratios and risk stratification</h1>

<img data-src="stroke_slides_files/figure-revealjs/unnamed-chunk-12-1.png" width="960" class="r-stretch"></section>
<section id="interpretation-forest-plot-odds-ratios" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — Forest Plot (Odds Ratios)</span></h2>
<div style="font-size:26px; line-height:1.25;">
<ul>
<li><p><strong>Hypertension</strong><br>
Strongest predictor. OR &gt; 2 with CI fully above 1 → hypertensive patients have <strong>more than double</strong> the odds of stroke.</p></li>
<li><p><strong>Age (per year)</strong><br>
OR slightly &gt; 1 with a narrow CI above 1 → each year adds a <strong>consistent increase</strong> in stroke risk.</p></li>
<li><p><strong>Average glucose level</strong><br>
OR just above 1 with CI above 1 → higher glucose gives a <strong>modest but reliable</strong> rise in stroke risk.</p></li>
<li><p><strong>Other predictors</strong> (ever married, heart disease, smoking, gender, BMI, residence, work type)<br>
CIs cross 1 → <strong>not statistically significant</strong> after adjustment.<br>
Some ORs are &gt; 1 (e.g., heart disease, smoking), suggesting possible risk, but evidence is weak in this dataset.</p></li>
</ul>
<p><strong>Overall:</strong><br>
Hypertension, older age, and higher glucose are the <strong>clearest independent predictors</strong> of stroke.<br>
Other factors show smaller or uncertain effects.<br>
This pattern aligns with known clinical risk factors and supports the logistic model’s value for risk stratification.</p>
</div>
</section>
<section id="threshold-tuning-to-0.2-from-0.5" class="slide level2 center">
<h2>Threshold tuning to 0.2 from 0.5</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  No Yes
       No  903  46
       Yes  46  13
                                          
               Accuracy : 0.9087          
                 95% CI : (0.8892, 0.9258)
    No Information Rate : 0.9415          
    P-Value [Acc &gt; NIR] : 1               
                                          
                  Kappa : 0.1719          
                                          
 Mcnemar's Test P-Value : 1               
                                          
            Sensitivity : 0.22034         
            Specificity : 0.95153         
         Pos Pred Value : 0.22034         
         Neg Pred Value : 0.95153         
             Prevalence : 0.05853         
         Detection Rate : 0.01290         
   Detection Prevalence : 0.05853         
      Balanced Accuracy : 0.58593         
                                          
       'Positive' Class : Yes             
                                          </code></pre>
</div>
</div>
</section>
<section id="interpretation-threshold-0.2" class="slide level2 center">
<h2><span style="font-size:34px;">Interpretation — Threshold = 0.2</span></h2>
<div style="font-size:26px; line-height:1.25;">
<ul>
<li><p>Sensitivity improves from <strong>1 stroke detected → 13/59 detected</strong><br>
(<strong>22%</strong>, up from 1.7%) when lowering the cutoff to 0.2.</p></li>
<li><p><strong>Specificity stays high (≈95%)</strong>, correctly classifying most non-stroke patients<br>
(<strong>903 out of 949</strong> remain correctly labeled).</p></li>
<li><p>Overall accuracy drops slightly (<strong>94% → 91%</strong>), but <strong>balanced accuracy improves</strong><br>
(<strong>≈0.51 → ≈0.59</strong>), reflecting better sensitivity–specificity trade-off.</p></li>
</ul>
<p><strong>Overall:</strong><br>
Lowering the threshold captures <strong>more true stroke cases</strong> with only a moderate increase in false positives — a clinically reasonable trade-off for early risk detection.</p>
</div>
</section>
<section id="conclusion" class="slide level2 center">
<h2><span style="font-size:34px;">Conclusion</span></h2>
<div style="font-size:26px; line-height:1.25;">
<ul>
<li><strong>Key Risk Factors Validated:</strong> <strong>Age, Hypertension, and Glucose</strong> confirmed as core, interpretable risk factors via Logistic Regression.</li>
<li><strong>Problem Solved:</strong> The initial failure (~2% Sensitivity) was fixed using <strong>SMOTE/ROSE</strong> resampling techniques.</li>
<li><strong>Diagnostic Success:</strong> Resampled models achieved clinically robust <strong>Sensitivity</strong> (~60-80%), demonstrating high performance for rare-event prediction.</li>
<li><strong>LR vs.&nbsp;ML Trade-off:</strong> <strong>Logistic Regression</strong> is best for <strong>explanation</strong> (ORs), but <strong>Random Forest/GBM with SMOTE/ROSE</strong> offers the highest <strong>predictive power</strong> (AUC/Sensitivity) for clinical decision-making.</li>
<li><strong>Next Steps:</strong> External validation and clinical integration of the resampled ML models.</li>
</ul>
</div>

</section>

</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="stroke_slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="stroke_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="stroke_slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="stroke_slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>